# Generated by Django 4.2.7 on 2023-12-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightPlaylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
